# Generated by Django 5.0.4 on 2024-05-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
