# Generated by Django 5.0.4 on 2024-05-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_remove_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
