# Generated by Django 5.0.4 on 2024-05-02 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('acceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptor_name', to='user.user')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiator_chat', to='user.user')),
            ],
        ),
    ]
