# Generated by Django 5.0.4 on 2024-05-05 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_table'),
        ('user', '0009_alter_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='acceptor',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='short_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-05 03:00:00.000 +0300'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='first_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.TextField(default=1, max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='second_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
