# Generated by Django 5.0.4 on 2024-05-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_acceptor_remove_chat_initiator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(max_length=2500, null=True),
        ),
    ]
